# Colors (Pencil Dark)

# Default Colors
[colors.primary]
background = '#000000'
#foreground = '#f1f1f1'
foreground = '#d5d5d5'

# Normal colors
[colors.normal]
black   = '#212121'
red     = '#c30771'
green   = '#10a778'
yellow  = '#a89c14'
blue    = '#008ec4'
#magenta = '#523c79'
magenta = '#7C3AED'
cyan    = '#20a5ba'
white   = '#e0e0e0'

# Bright colors
[colors.bright]
black   = '#818181'
red     = '#fb007a'
green   = '#5fd7af'
yellow  = '#f3e430'
blue    = '#20bbfc'
#magenta = '#6855de'
magenta = '#A88BFA'
cyan    = '#4fb8cc'
white   = '#f1f1f1'
